export const ActionTypes = {
  FETCHING_SMURFS: 'FETCHING_SMURFS',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  ADD_SMURF: 'ADD_SMURF',
  ADD_SUCCESS: 'ADD_SMURF_SUCCESS',
  ADD_ERROR: 'ADD_ERROR',
  FORM_ERROR: 'FORM_ERROR',
};
